version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/packages/core"
    schedule:
      interval: "daily"
    target-branch: "dev"
    labels:
      - "dependencies"
  - package-ecosystem: "npm"
    directory: "/packages/adapter-standalone"
    schedule:
      interval: "daily"
    target-branch: "dev"
    labels:
      - "dependencies"
