version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/packages/core"
    schedule:
      interval: "daily"
    target-branch: "dev"
    labels:
      - "dependencies"
  - package-ecosystem: "npm"
    directory: "/packages/adapter-standalone"
    schedule:
      interval: "daily"
    target-branch: "dev"
    labels:
      - "dependencies"
  - package-ecosystem: "npm"
    directory: "/packages/dev-server"
    schedule:
      interval: "daily"
    target-branch: "dev"
    labels:
      - "dependencies"
  - package-ecosystem: "npm"
    directory: "/packages/cli"
    schedule:
      interval: "daily"
    target-branch: "dev"
    labels:
      - "dependencies"
  - package-ecosystem: "npm"
    directory: "/packages/create-svarta-app"
    schedule:
      interval: "daily"
    target-branch: "dev"
    labels:
      - "dependencies"
