name: Deploy page

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        node-version:
          - 16.x
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: cd docs && pnpm install
      - name: Generate page
        run: cd docs && pnpm generate
      - name: Deploy page
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/.output/public
